extends Node
## Audio autoload: music crossfade + UI one-shot sounds.
##
## Music: Audio.play_music("menu") / Audio.play_music("battle") — re-calling the
## current track is a no-op, so every screen can declare its track in _ready and
## the music only changes (with a crossfade) when the destination differs.
## UI: Audio.ui("move" / "confirm" / "back") from any menu screen.
## Tracks/sounds are generated by scripts/tools/gen_music.py / gen_sfx.py;
## missing files are skipped silently so audio can land piecemeal.

const TRACKS := {
	"menu": "res://assets/music/menu_theme.mp3",
	"battle": "res://assets/music/battle_theme.mp3",
}
const UI_SOUNDS := {
	"move": "res://assets/sfx/ui_move.wav",
	"confirm": "res://assets/sfx/ui_confirm.wav",
	"back": "res://assets/sfx/ui_back.wav",
}
const CROSSFADE := 0.7
const SILENT_DB := -42.0

var _players: Array[AudioStreamPlayer] = []
var _active := 0          # index into _players of the one carrying the music
var _current_track := ""
var _ui_players: Dictionary = {}

func _ready() -> void:
	process_mode = PROCESS_MODE_ALWAYS  # music keeps playing under Pause
	for i in 2:
		var p := AudioStreamPlayer.new()
		p.bus = "Music"
		p.volume_db = SILENT_DB
		add_child(p)
		_players.append(p)
	for key in UI_SOUNDS:
		if not ResourceLoader.exists(UI_SOUNDS[key]):
			continue
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		p.stream = load(UI_SOUNDS[key])
		add_child(p)
		_ui_players[key] = p

func play_music(track: String) -> void:
	if track == _current_track:
		return
	if not TRACKS.has(track) or not ResourceLoader.exists(TRACKS[track]):
		stop_music()
		_current_track = track
		return
	_current_track = track
	var from := _players[_active]
	_active = 1 - _active
	var to := _players[_active]
	# CACHE_MODE_IGNORE: the audio thread can hold the stream past tree teardown,
	# and a cached ref then trips "resources still in use" on every quit.
	to.stream = ResourceLoader.load(TRACKS[track], "", ResourceLoader.CACHE_MODE_IGNORE)
	# Force seamless looping regardless of the .ogg's import settings (the JRPG
	# tracks are composed to loop). AudioStreamOggVorbis/WAV both expose `loop`.
	if to.stream != null and "loop" in to.stream:
		to.stream.loop = true
	to.volume_db = SILENT_DB
	to.play()
	var tw := create_tween()
	tw.tween_property(to, "volume_db", 0.0, CROSSFADE)
	if from.playing:
		tw.parallel().tween_property(from, "volume_db", SILENT_DB, CROSSFADE)
		tw.chain().tween_callback(from.stop)

func stop_music(fade := CROSSFADE) -> void:
	_current_track = ""
	var from := _players[_active]
	if not from.playing:
		return
	var tw := create_tween()
	tw.tween_property(from, "volume_db", SILENT_DB, fade)
	tw.chain().tween_callback(from.stop)

func ui(sound: String) -> void:
	var p: AudioStreamPlayer = _ui_players.get(sound)
	if p == null:
		return
	p.pitch_scale = randf_range(0.97, 1.03)
	p.play()
